#! /bin/sh
# colors
for dircolors in gdircolors dircolors ; do
	if command -v $dircolors >/dev/null 2>&1 ; then
		dircolor_text=''
		if [ -f "${HOME}/.dir_colors" ] ; then
			dircolor_text=`cat "${HOME}/.dir_colors"`
		elif [ -f /etc/DIR_COLORS ] ; then
			dircolor_text=`cat /etc/DIR_COLORS`
		fi

		if $dircolors --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			dircolor_text="${dircolor_text}\nSTICKY_OTHER_WRITABLE 01;04;34;40"
			dircolor_text="${dircolor_text}\nOTHER_WRITABLE 01;34;40"
		fi

		eval `echo "${dircolor_text}" | $dircolors -b -`
		break
	fi
done

# gimmie an editor, and make it emacs24
for EDITOR in $(where emacs); do
	$EDITOR -version | grep 24 >/dev/null && break
done
EDITOR="${EDITOR} -nw"
export EDITOR

# make the history editor the editor we want
FCEDIT=$EDITOR
export FCEDIT

# vimx -> vim
if [ "${EDITOR}" = vimx ] ; then
	alias vim=vimx
fi

# display emacs in-terminal by default
alias emacs='emacs -nw'
alias emacsx='\emacs'

# Typo corrections
alias cd..='cd ..'
alias sl='ls'

# handles per OS aliases, fixes a few terms
case `uname -s` in
	Linux|CYGWIN*)
		alias ls="ls -h --color=auto"
		alias grep='grep -d skip --color=auto'
	;;
	FreeBSD|Darwin|DragonFly)
		if command -v top >/dev/null 2>&1 ; then
			alias top="top -o cpu"
		fi

		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			LSCOLORS="ExGxFxDxCxDxDxHbaDEaEa"
			export LSCOLORS
			alias ls="ls -Gh"
		fi
		alias grep='grep -d skip --color=auto'
	;;
	Interix)
		alias ls="ls --color"
	;;
	SunOS)
		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			alias ls="ls -h"
		fi

		if command -v ggrep >/dev/null 2>&1 ; then
			alias grep='ggrep -d skip --color=auto'
		elif grep --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias grep='grep -d skip --color=auto'
		fi

		for locate in glocate slocate ; do
			command -v $locate >/dev/null 2>&1 && alias locate=$locate
		done
	;;
esac

if command -v gobjdump >/dev/null 2>&1 ; then
	alias objdump=gobjdump
fi

if command -v ack-grep >/dev/null 2>&1 ; then
	alias ack=ack-grep
fi

mps () {
	ps -Aww | grep -E "[0-9]{2} [-_/\.\(\)\\ a-zA-Z0-9]*$1[-_/\.\(\)\\ a-zA-Z0-9]*" --color=NEVER
}
crc32 () {
	cksum -o3 "$@" | perl -wane 'printf "%s %08x\n", $F[2], $F[0]'
}
rgrep () {
	grep -R --color=always "$*" .
}

# "WTF is going on (with my machine)"
wtfigo () {
	case $(uname) in
		Linux)
			watch vmstat -S M
		;;
		# TODO: Darwin
	esac
}

emacs-recompile () {
	emacs --batch --eval '(byte-recompile-directory (expand-file-name ".") 0)'
}

resource () {
	# TODO: generalize
	source ~/.zshrc
}

alias rm='rm -i'
alias df='df -h'
alias du='du -h'
alias ping='ping -c4'
if command -v autossh >/dev/null 2>&1; then
	alias ssh='autossh -M 0'
fi

alias mdu='du -d 1 -h'
alias mls='ls -lhFA'
alias mrm='rm -rf'
alias mtop='top -o cpu'
alias mdiff='diff -ubE'
alias mg='rgrep'
alias mfe='free -m'

alias e='emacs'
alias g='git'

alias ga='git add'
alias gs='git status'
alias gi='git commit'
alias gc='git checkout'
alias gb='git branch'
alias gpl='git pull'
alias gps='git push'
alias gsh='git stash'
alias gr='git rebase'
alias gm='git merge'

alias cscope='cscope -bR'
alias ctags-c++='ctags -R --c++-kinds=+p --fields=+iaS --extra=+q'
alias maketex="make -f ${HOME}/.latex/Makefile"

command -v time >/dev/null 2>&1 && alias time='command time'
