#! /bin/sh

# colors
for dircolors in gdircolors dircolors ; do
	if command -v $dircolors >/dev/null 2>&1 ; then
		dircolor_text=''
		if [ -f "${HOME}/.dir_colors" ] ; then
			dircolor_text=`cat "${HOME}/.dir_colors"`
		elif [ -f /etc/DIR_COLORS ] ; then
			dircolor_text=`cat /etc/DIR_COLORS`
		fi

		if $dircolors --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			dircolor_text="${dircolor_text}\nSTICKY_OTHER_WRITABLE 01;04;34;40"
			dircolor_text="${dircolor_text}\nOTHER_WRITABLE 01;34;40"
		fi

		eval `echo "${dircolor_text}" | $dircolors -b -`
		break
	fi
done

# gimmie an editor, and make it emacs24
for EDITOR in $(where emacs | grep -vE "aliased to"); do
	$EDITOR -version | grep 24 >/dev/null && break
done
#EDITOR="${EDITOR} -nw"
EDITOR="emacsclient"
export EDITOR

# make the history editor the editor we want
FCEDIT=$EDITOR
export FCEDIT

# vimx -> vim
if [ "${EDITOR}" = vimx ] ; then
	alias vim=vimx
fi

# display emacs in-terminal by default
alias emacs='TERM=xterm-16color emacs -nw'
alias emacsclient='TERM=xterm-16color emacsclient -nw --alternate-editor=""'
alias xemacs='TERM=xterm-16color \emacs'

# Common typos
alias cd..='cd ..'
alias sl='ls'

# handles per OS aliases, fixes a few terms
case `uname -s` in
	Linux|CYGWIN*)
		alias ls="ls -h --color=auto"
		alias grep='grep -d skip --color=auto'
	;;
	FreeBSD|Darwin|DragonFly)
		if command -v top >/dev/null 2>&1 ; then
			alias top="top -o cpu"
		fi

		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			LSCOLORS="exgxfxdxcxdxdxhbadeaea"
			export LSCOLORS
			alias ls="ls -Gh"
		fi
		alias grep='grep -d skip --color=auto'
	;;
	Interix)
		alias ls="ls --color"
	;;
	SunOS)
		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			alias ls="ls -h"
		fi

		if command -v ggrep >/dev/null 2>&1 ; then
			alias grep='ggrep -d skip --color=auto'
		elif grep --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias grep='grep -d skip --color=auto'
		fi

		for locate in glocate slocate ; do
			command -v $locate >/dev/null 2>&1 && alias locate=$locate
		done
	;;
esac

if command -v gobjdump >/dev/null 2>&1 ; then
	alias objdump=gobjdump
fi

if command -v ack-grep >/dev/null 2>&1 ; then
	alias ack=ack-grep
fi

mps () {
	ps -Aww | grep -E "[0-9]{2} [-_/\.\(\)\\ a-zA-Z0-9]*$1[-_/\.\(\)\\ a-zA-Z0-9]*" --color=NEVER
}
crc32 () {
	cksum -o3 "$@" | perl -wane 'printf "%s %08x\n", $F[2], $F[0]'
}
rgrep () {
	grep -R --color=always "$*" .
}

# "WTF is going on (with my machine)"
wtfigo () {
	case $(uname) in
		Linux)
			watch vmstat -S M
		;;
		# TODO: Darwin
	esac
}

emacs-recompile () {
	emacs --batch --eval '(byte-recompile-directory (expand-file-name ".") 0)'
}

resource () {
	# TODO: generalize
	source ~/.zshrc
}

make-alias () {
    echo -n "\nalias ${1}='${@:2}'" | cat ~/dotfiles/commonsh/11_alias - | LC_ALL=ASCII sort -u | sed '/^$/d' > ~/dotfiles/commonsh/.11_alias_tmp
    mv ~/dotfiles/commonsh/.11_alias_tmp ~/dotfiles/commonsh/11_alias
    chmod +x ~/dotfiles/commonsh/11_alias
    resource
} 

command -v time >/dev/null 2>&1 && alias time='command time'
